#!/bin/bash

if [ "$1" == "output" ]; then
  cat state.db
else
  echo "$*" > state.db

  if [[ "$1" == "plan" ]]; then
    touch ink.plan
  fi
fi

if [ -n "$TF_VAR_TEST_EXIT" ]; then
  exit $TF_VAR_TEST_EXIT
elif [ -n "$INK_TEST_EXIT" ]; then
  exit $INK_TEST_EXIT
else
  exit 0
fi
